services:
  simpleaccounts:
    build: .
    restart: unless-stopped

    depends_on:
      - psql
      - redis

    environment:
      SIMPLEACCOUNTS_PSQL_URI: postgres://${SIMPLEACCOUNTS_PSQL_USER}:${SIMPLEACCOUNTS_PSQL_PASSWORD}@psql/simpleaccounts
      SIMPLEACCOUNTS_REDIS_URI: redis://redis/

    ports:
      - 8080:8080

    networks:
      - simple-accounts-net

  psql:
    image: postgres:alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${SIMPLEACCOUNTS_PSQL_USER}
      POSTGRES_PASSWORD: ${SIMPLEACCOUNTS_PSQL_PASSWORD}
      POSTGRES_DB: simpleaccounts

    volumes:
      - ./psql:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/1.sql

    ports:
      - 5432:5432

    networks:
      - simple-accounts-net

  redis:
    image: redis:alpine
    restart: unless-stopped

    volumes:
      - ./redis:/data

    networks:
      - simple-accounts-net

networks:
  simple-accounts-net:
    driver: bridge
